#!/usr/bin/env python3
"""Build the self-contained interactive mission viewer.

Reads output/moonshot_*.csv and writes output/moonshot_viewer.html — a
zero-dependency HTML page with a canvas 3D scene of the circumlunar
trajectory: drag to orbit the camera, scroll to zoom, play/scrub mission
time, and toggle between the inertial and Earth-Moon rotating frames.

Usage: python3 scripts/make_viewer.py
"""
import csv
import json
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "output")


def read_csv(path):
    with open(path) as f:
        rows = list(csv.reader(f))
    hdr = rows[0]
    arr = np.array([[float(v) if v not in ("", "NaN") else np.nan for v in r]
                    for r in rows[1:]])
    return {h: arr[:, i] for i, h in enumerate(hdr)}


cis = read_csv(os.path.join(OUT, "moonshot_cislunar.csv"))

# project into the mission plane (planar mission; checked < 1 km out-of-plane)
M = np.stack([cis["moon_x_m"], cis["moon_y_m"], cis["moon_z_m"]], axis=1) / 1e6
R3 = np.stack([cis["x_m"], cis["y_m"], cis["z_m"]], axis=1) / 1e6
b1 = M[0] / np.linalg.norm(M[0])
n = np.cross(M[0], M[len(M) // 3])
n = n / np.linalg.norm(n)
b2 = np.cross(n, b1)
P = np.stack([b1, b2])                      # world -> plane (2D)
traj = R3 @ P.T                             # [N,2] in 1000 km
moon = M @ P.T

t = cis["t_s"]
ph = cis["phase"].astype(int)

data = {
    "t": [round(float(v), 1) for v in t],
    "x": [round(float(v), 3) for v in traj[:, 0]],
    "y": [round(float(v), 3) for v in traj[:, 1]],
    "mx": [round(float(v), 3) for v in moon[:, 0]],
    "my": [round(float(v), 3) for v in moon[:, 1]],
    "ph": [int(v) for v in ph],
}

events = []
with open(os.path.join(OUT, "moonshot_events.csv")) as f:
    for row in csv.DictReader(f):
        events.append({"phase": row["phase"], "event": row["event"],
                       "t": float(row["t_s"])})
data["events"] = events

summary = open(os.path.join(OUT, "moonshot_summary.txt"), encoding="utf-8").read()

# pull the headline tiles out of the summary so they track the actual run
import re


def grab(pattern, default="?"):
    m = re.search(pattern, summary)
    return m.group(1) if m else default


tiles = {
    "LIFTOFF": grab(r"Liftoff mass\s*:\s*([\d.]+ t)"),
    "TLIDV": grab(r"dv=([\d.]+) m/s"),
    "PERILUNE": grab(r"Perilune\s*:\s*([\d]+) km"),
    "ENTRYV": grab(r"V_rel=([\d]+) m/s"),
    "PEAKG": grab(r"peak load\s*:\s*([\d.]+) g"),
    "DAYS": grab(r"Splashdown.*t=([\d.]+) d"),
}

html = """<!-- generated by scripts/make_viewer.py -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ss.jl — Circumlunar Free Return</title>
<style>
  :root { color-scheme: dark; }
  body { margin: 0; background: #0d0d0d; color: #c3c2b7;
         font: 14px/1.45 system-ui, -apple-system, "Segoe UI", sans-serif; }
  .wrap { max-width: 1080px; margin: 0 auto; padding: 18px; }
  h1 { color: #fff; font-size: 20px; margin: 4px 0 2px; }
  .sub { color: #898781; font-size: 13px; margin-bottom: 12px; }
  .tiles { display: flex; flex-wrap: wrap; gap: 10px; margin: 12px 0; }
  .tile { background: #1a1a19; border: 1px solid rgba(255,255,255,.1);
          border-radius: 8px; padding: 8px 14px; min-width: 108px; }
  .tile .v { color: #fff; font-size: 19px; font-weight: 650; }
  .tile .k { color: #898781; font-size: 11px; }
  #stage { position: relative; background: #1a1a19; border-radius: 10px;
           border: 1px solid rgba(255,255,255,.1); overflow: hidden; }
  canvas { display: block; width: 100%; cursor: grab; touch-action: none; }
  .bar { display: flex; gap: 10px; align-items: center; padding: 10px 12px;
         border-top: 1px solid rgba(255,255,255,.08); flex-wrap: wrap; }
  button { background: #2a2a28; color: #fff; border: 1px solid rgba(255,255,255,.15);
           border-radius: 6px; padding: 5px 14px; font: inherit; cursor: pointer; }
  button:hover { background: #383835; }
  button.on { background: #3987e5; border-color: #3987e5; }
  input[type=range] { flex: 1; min-width: 160px; accent-color: #3987e5; }
  .ro { font-variant-numeric: tabular-nums; color: #c3c2b7; font-size: 12.5px;
        min-width: 210px; }
  .legend { display: flex; gap: 14px; padding: 8px 12px 2px; font-size: 12px;
            color: #c3c2b7; flex-wrap: wrap; }
  .legend i { display: inline-block; width: 14px; height: 3px; border-radius: 2px;
              vertical-align: middle; margin-right: 5px; }
  pre { background: #1a1a19; border: 1px solid rgba(255,255,255,.1);
        border-radius: 8px; padding: 12px 14px; font-size: 12px; color: #c3c2b7;
        overflow-x: auto; }
  .hint { color: #898781; font-size: 12px; padding: 0 12px 10px; }
</style>
<div class="wrap">
  <h1>Circumlunar free-return mission</h1>
  <div class="sub">SatelliteSim.jl — launch &rarr; 200 km parking orbit &rarr; TLI &rarr;
    2000 km lunar flyby &rarr; ballistic entry at 10.6 km/s &rarr; Pacific splashdown</div>

  <div class="tiles">
    <div class="tile"><div class="v">__LIFTOFF__</div><div class="k">liftoff mass</div></div>
    <div class="tile"><div class="v">__TLIDV__ m/s</div><div class="k">TLI &Delta;v</div></div>
    <div class="tile"><div class="v">__PERILUNE__ km</div><div class="k">perilune altitude</div></div>
    <div class="tile"><div class="v">__ENTRYV__ m/s</div><div class="k">entry speed</div></div>
    <div class="tile"><div class="v">__PEAKG__ g</div><div class="k">peak entry load</div></div>
    <div class="tile"><div class="v">__DAYS__ d</div><div class="k">mission duration</div></div>
  </div>

  <div id="stage">
    <div class="legend">
      <span><i style="background:#3987e5"></i>parking orbit</span>
      <span><i style="background:#d95926"></i>TLI burn</span>
      <span><i style="background:#199e70"></i>outbound</span>
      <span><i style="background:#c98500"></i>return</span>
      <span><i style="background:#6b6b66;height:8px;width:8px;border-radius:50%"></i>Moon</span>
    </div>
    <canvas id="cv" height="620"></canvas>
    <div class="bar">
      <button id="play">&#9654; play</button>
      <input id="scrub" type="range" min="0" max="1000" value="1000">
      <button id="frame">rotating frame</button>
      <span class="ro" id="readout"></span>
    </div>
    <div class="hint">drag to tilt &middot; scroll / pinch to zoom &middot; rotating
      frame pins the Earth&ndash;Moon line horizontal (the figure-8 view)</div>
  </div>

  <h1 style="font-size:16px;margin-top:22px">Mission summary</h1>
  <pre>__SUMMARY__</pre>
</div>
<script>
const D = __DATA__;
const N = D.t.length;
const cv = document.getElementById('cv');
const ctx = cv.getContext('2d');
const COL = {0:'#3987e5', 1:'#d95926', 2:'#199e70', 3:'#c98500'};
const RE = 6.371, RM = 1.7374;              // in 1000 km

let rotFrame = false;
let camYaw = 0, camPitch = 1.05, camDist = 1150;
let ti = 0;                                  // current sample index
let playing = false, lastTs = 0;

// precompute rotating-frame coordinates (rotate by -moon angle)
const rx = new Float64Array(N), ry = new Float64Array(N);
const ma = new Float64Array(N);
for (let i = 0; i < N; i++) {
  ma[i] = Math.atan2(D.my[i], D.mx[i]);
  const c = Math.cos(-ma[i]), s = Math.sin(-ma[i]);
  rx[i] = D.x[i]*c - D.y[i]*s;
  ry[i] = D.x[i]*s + D.y[i]*c;
}
const moonR = Math.hypot(D.mx[0], D.my[0]);

function P(i) {   // scene position of pod sample i
  return rotFrame ? [rx[i], ry[i]] : [D.x[i], D.y[i]];
}
function Pm(i) {  // scene position of the Moon
  return rotFrame ? [moonR, 0] : [D.mx[i], D.my[i]];
}

// ------------------------------------------------------------- starfield --
// The sky is at infinity, so it belongs to the CAMERA, not the canvas: these
// stars are real directions on a celestial sphere, projected gnomonically
// through the same yaw/pitch the scene uses. Drag and the sky swings with the
// view; zoom and it holds still, which is what an infinitely distant sky does.
// (The previous version was 90 fixed screen-space pixels — they sat where
// they were painted however the camera moved, which read as dirt on the
// monitor rather than as stars.)
// Most of these are off-screen on any given frame; the cull is three dot
// products, and only the survivors ever touch the 2D context.
const NSTAR = 4200;
const SKY = (() => {
  let s = 20250724;                        // fixed seed: same sky every load
  const rnd = () => (s = (s*1103515245 + 12345) & 0x7fffffff)/0x7fffffff;
  // galactic plane: an arbitrary but fixed pole, so the band sits still
  const gp = [0.3714, 0.8571, 0.3571];
  const ga = [-0.9226, 0.3857, 0.0]; // in-plane basis (perp to gp)
  const gb = [gp[1]*ga[2]-gp[2]*ga[1], gp[2]*ga[0]-gp[0]*ga[2],
              gp[0]*ga[1]-gp[1]*ga[0]];
  const stars = [], band = [];
  for (let i = 0; i < NSTAR; i++) {
    // uniform on the sphere, then pulled toward the galactic plane for a
    // third of them so the band has its own star excess
    let z = 2*rnd() - 1, th = 2*Math.PI*rnd();
    if (i % 3 === 0) z *= 0.13;
    const r = Math.sqrt(Math.max(0, 1 - z*z));
    const d = [ga[0]*r*Math.cos(th) + gb[0]*r*Math.sin(th) + gp[0]*z,
               ga[1]*r*Math.cos(th) + gb[1]*r*Math.sin(th) + gp[1]*z,
               ga[2]*r*Math.cos(th) + gb[2]*r*Math.sin(th) + gp[2]*z];
    const mag = Math.pow(rnd(), 3.4);      // few bright, many faint
    const t = rnd()*2 - 1;
    const tint = Math.sign(t)*Math.pow(Math.abs(t), 1.9);
    // near-white with amber and blue tails, as a real field reads
    const c = tint < 0
      ? [255, 255 + tint*62, 255 + tint*122]
      : [255 - tint*72, 255 - tint*46, 255];
    stars.push({d, mag, c: `${c[0]|0},${c[1]|0},${c[2]|0}`});
  }
  // Diffuse band light: overlapping soft patches sized in ANGLE, not pixels,
  // so they scale with the projection and merge into one glow. Sparse or
  // pixel-sized, they read as smudges on the lens instead.
  // Few and large rather than many and small: each gradient the browser
  // composites carries its own dither, and 300 of them stacked at alpha 0.02
  // print a visible checkerboard across the band.
  for (let i = 0; i < 120; i++) {
    const z = (rnd() + rnd() + rnd() - 1.5)*0.11, th = 2*Math.PI*rnd();
    const r = Math.sqrt(Math.max(0, 1 - z*z));
    band.push({d: [ga[0]*r*Math.cos(th) + gb[0]*r*Math.sin(th) + gp[0]*z,
                   ga[1]*r*Math.cos(th) + gb[1]*r*Math.sin(th) + gp[1]*z,
                   ga[2]*r*Math.cos(th) + gb[2]*r*Math.sin(th) + gp[2]*z],
               ang: 0.17 + 0.24*rnd(), a: 0.010 + 0.015*rnd()});
  }
  return {stars, band};
})();

// camera basis matching project(): right, up, and the view direction
function skyBasis() {
  const cy = Math.cos(camYaw), sy = Math.sin(camYaw);
  const cp = Math.cos(camPitch), sp = Math.sin(camPitch);
  return {r: [cy, -sy, 0], u: [sy*sp, cy*sp, cp], w: [sy*cp, cy*cp, -sp]};
}

function drawSky(w, h) {
  const B = skyBasis();
  const f = 0.95*Math.max(w, h);           // synthetic focal length [px]
  const dot = (a, b) => a[0]*b[0] + a[1]*b[1] + a[2]*b[2];
  const put = (d) => {
    const z = dot(d, B.w);
    if (z < 0.30) return null;             // behind us, or too far off-axis
    return [w/2 + f*dot(d, B.r)/z, h*0.52 - f*dot(d, B.u)/z];
  };
  // unresolved band light first, so stars sit on top of it
  for (const b of SKY.band) {
    const z = dot(b.d, B.w);
    if (z < 0.30) continue;
    const p = [w/2 + f*dot(b.d, B.r)/z, h*0.52 - f*dot(b.d, B.u)/z];
    const s = f*b.ang/z;
    if (p[0] < -s || p[0] > w+s || p[1] < -s || p[1] > h+s) continue;
    const g = ctx.createRadialGradient(p[0], p[1], 0, p[0], p[1], s);
    g.addColorStop(0, `rgba(176,186,214,${b.a})`);
    g.addColorStop(1, 'rgba(176,186,214,0)');
    ctx.fillStyle = g;
    ctx.fillRect(p[0]-s, p[1]-s, 2*s, 2*s);
  }
  for (const st of SKY.stars) {
    const p = put(st.d);
    if (!p) continue;
    if (p[0] < -4 || p[0] > w+4 || p[1] < -4 || p[1] > h+4) continue;
    const a = 0.26 + 0.70*st.mag;
    const rr = 0.5 + 1.3*st.mag;
    if (st.mag > 0.55) {                   // the bright ones get a soft bloom
      const gr = rr*4.5;
      const g = ctx.createRadialGradient(p[0], p[1], 0, p[0], p[1], gr);
      g.addColorStop(0, `rgba(${st.c},${a*0.32})`);
      g.addColorStop(1, `rgba(${st.c},0)`);
      ctx.fillStyle = g;
      ctx.fillRect(p[0]-gr, p[1]-gr, 2*gr, 2*gr);
    }
    ctx.fillStyle = `rgba(${st.c},${a})`;
    if (rr < 0.75) {                       // the faint majority: cheapest path
      ctx.fillRect(p[0], p[1], 1, 1);
    } else {
      ctx.beginPath();
      ctx.arc(p[0], p[1], rr, 0, 2*Math.PI);
      ctx.fill();
    }
  }
}

function project(x, y) {
  // camera: orbit about origin, looking at origin; z=0 plane scene
  const cy = Math.cos(camYaw), sy = Math.sin(camYaw);
  const cp = Math.cos(camPitch), sp = Math.sin(camPitch);
  let X = x*cy - y*sy, Y = x*sy + y*cy;
  let Z = Y*cp;         // tilt
  Y = Y*sp;
  const w = cv.width / (window.devicePixelRatio||1), h = cv.height / (window.devicePixelRatio||1);
  const f = Math.min(w, h) * 0.95 / camDist;
  return [w/2 + X*f, h*0.52 - Y*f, f];
}

function circle(x, y, r, fill) {
  ctx.beginPath(); ctx.arc(x, y, r, 0, 2*Math.PI); ctx.fillStyle = fill; ctx.fill();
}

function draw() {
  const dpr = window.devicePixelRatio || 1;
  const w = cv.clientWidth;
  if (cv.width !== w*dpr) { cv.width = w*dpr; cv.height = 620*dpr; }
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  ctx.clearRect(0, 0, w, 620);

  drawSky(w, 620);

  // moon orbit
  ctx.strokeStyle = '#2c2c2a'; ctx.lineWidth = 1;
  ctx.beginPath();
  for (let a = 0; a <= 128; a++) {
    const th = a/128*2*Math.PI;
    const p = rotFrame ? project(moonR*Math.cos(th), moonR*Math.sin(th))
                       : project(moonR*Math.cos(th), moonR*Math.sin(th));
    if (a === 0) ctx.moveTo(p[0], p[1]); else ctx.lineTo(p[0], p[1]);
  }
  ctx.stroke();

  // trajectory up to current time, per phase
  ctx.lineCap = 'round';
  let prev = null, prevPh = -1;
  for (let i = 0; i <= ti; i++) {
    const pos = P(i);
    const pr = project(pos[0], pos[1]);
    if (prev) {
      ctx.strokeStyle = COL[D.ph[i]] || '#c3c2b7';
      ctx.lineWidth = D.ph[i] === 1 ? 3 : 1.8;
      ctx.beginPath(); ctx.moveTo(prev[0], prev[1]); ctx.lineTo(pr[0], pr[1]); ctx.stroke();
    }
    prev = pr;
  }
  // faint remainder of the path
  ctx.globalAlpha = 0.18;
  for (let i = ti+1; i < N; i++) {
    const pos = P(i);
    const pr = project(pos[0], pos[1]);
    if (prev) {
      ctx.strokeStyle = COL[D.ph[i]] || '#c3c2b7';
      ctx.lineWidth = 1.2;
      ctx.beginPath(); ctx.moveTo(prev[0], prev[1]); ctx.lineTo(pr[0], pr[1]); ctx.stroke();
    }
    prev = pr;
  }
  ctx.globalAlpha = 1;

  // Earth
  const pe = project(0, 0);
  const rEarth = Math.max(3.5, RE*pe[2]);
  const g = ctx.createRadialGradient(pe[0]-rEarth*.3, pe[1]-rEarth*.3, rEarth*.2, pe[0], pe[1], rEarth);
  g.addColorStop(0, '#4a7fa8'); g.addColorStop(1, '#193349');
  circle(pe[0], pe[1], rEarth, g);

  // Moon
  const pmv = Pm(ti);
  const pm = project(pmv[0], pmv[1]);
  const rMoon = Math.max(2.5, RM*pm[2]*3);
  const g2 = ctx.createRadialGradient(pm[0]-rMoon*.3, pm[1]-rMoon*.3, rMoon*.2, pm[0], pm[1], rMoon);
  g2.addColorStop(0, '#8d8d86'); g2.addColorStop(1, '#4a4a45');
  circle(pm[0], pm[1], rMoon, g2);

  // pod
  const pp = P(ti);
  const pd = project(pp[0], pp[1]);
  ctx.strokeStyle = '#fff';
  circle(pd[0], pd[1], 3.4, '#fff');

  // readout
  const days = D.t[ti]/86400;
  const dm = Math.hypot(D.x[ti]-D.mx[ti], D.y[ti]-D.my[ti]);
  const rE = Math.hypot(D.x[ti], D.y[ti]);
  document.getElementById('readout').textContent =
    `T+${days.toFixed(2)} d · r⊕ ${(rE).toFixed(0)}k km · Moon ${(dm).toFixed(0)}k km`;
}

function step(ts) {
  if (playing) {
    const dt = Math.min(50, ts - lastTs);
    ti = Math.min(N-1, ti + Math.max(1, Math.round(dt/16 * N/900)));
    document.getElementById('scrub').value = (1000*ti/(N-1))|0;
    if (ti >= N-1) togglePlay(false);
  }
  lastTs = ts;
  draw();
  requestAnimationFrame(step);
}

function togglePlay(on) {
  playing = on === undefined ? !playing : on;
  if (playing && ti >= N-1) ti = 0;
  document.getElementById('play').innerHTML = playing ? '&#10074;&#10074; pause' : '&#9654; play';
}

document.getElementById('play').onclick = () => togglePlay();
document.getElementById('scrub').oninput = e => { ti = Math.round(e.target.value/1000*(N-1)); };
document.getElementById('frame').onclick = e => {
  rotFrame = !rotFrame;
  e.target.classList.toggle('on', rotFrame);
  e.target.textContent = rotFrame ? 'inertial frame' : 'rotating frame';
};

let drag = null;
cv.addEventListener('pointerdown', e => { drag = [e.clientX, e.clientY]; cv.setPointerCapture(e.pointerId); });
cv.addEventListener('pointermove', e => {
  if (!drag) return;
  camYaw += (e.clientX - drag[0]) * 0.005;
  camPitch = Math.min(1.55, Math.max(0.15, camPitch + (e.clientY - drag[1]) * 0.004));
  drag = [e.clientX, e.clientY];
});
cv.addEventListener('pointerup', () => drag = null);
cv.addEventListener('wheel', e => {
  e.preventDefault();
  camDist = Math.min(2400, Math.max(30, camDist * (e.deltaY > 0 ? 1.12 : 0.89)));
}, { passive: false });

ti = N-1;
requestAnimationFrame(step);
</script>
"""

html = html.replace("__DATA__", json.dumps(data, separators=(",", ":")))
html = html.replace("__SUMMARY__", summary.replace("<", "&lt;"))
for key, val in tiles.items():
    html = html.replace(f"__{key}__", val)

path = os.path.join(OUT, "moonshot_viewer.html")
with open(path, "w", encoding="utf-8") as f:
    f.write(html)
print("wrote", path, f"({os.path.getsize(path)//1024} KB)")
